### ISSUE TITLE
error on <style lang="styl">

### ISSUE THREAD

**Issue by retrogradeMT** [vue-bulma/quill#1]
on compiling, I get the error: Module not found: Error: Can't resolve 'styl' .  When I change "styl"  to stylus, everything works.    I'm wondering if that is a typo or if I am missing a loader?

**Comment by rmp135** [comment]
Vue determines which loader to use based on the lang. So `lang=stylus` will use the stylus-loader.

To change this, edit your webpack.config file to include the following on the same level as the entry properties.

``` javascript
entry: { ... },
vue: {
  loaders: {
    styl: 'vue-style!css!stylus'
  }
},
module: { ... }
```

**Comment by retrogradeMT** [comment]
Oh, I see.  I figured it was something like that.   Thank you
