### ISSUE TITLE
Fetching data from quill

### ISSUE THREAD

**Issue by retrogradeMT** [vue-bulma/quill#2]
I know this isn't a issue or bug, but I can't find an example of fetching the data from quill without using jquery.    So, how do I pass the data from this quill component back to the parent?

**Comment by rmp135** [comment]
There's a couple of options here.

The first is to set a `ref` on the quill component element thus.

``` javascript
<quill ref="qc"></quill>
```

This will allow you to access the component through the `this.$refs` property.

Use it as below

``` javascript
this.$refs.qc.$el.querySelector('.ql-editor').innerHTML;

this.$refs.qc.editor.getText();
```

It's a little hacky but doesn't require changing the component code.

---

Alternatively, you or the developer could add an event to component that is fired when the `text-change` event is emitted from Quill. This will enable the use of a `v-model` on the quill component.

Pick one of the following.

``` javascript
this.editor.on('text-change', () => this.$emit('input', { target: { value: this.$el.querySelector('.ql-editor').innerHTML }});

this.editor.on('text-change', () => this.$emit('input', { target: { value: this.editor.getText() }});
```

**Comment by retrogradeMT** [comment]
@rmp135 - Nice!  Thanks for the help,  I didn't know about refs.  At this point, everything I do is at least a little hacky.  This works great.

**Comment by salipro4ever** [comment]
somethings for that
```
editor.on('text-change', function() {
  var delta = editor.getContents();
  var text = editor.getText();
  var justHtml = editor.root.innerHTML;
  preciousContent.innerHTML = JSON.stringify(delta);
  justTextContent.innerHTML = text;
  justHtmlContent.innerHTML = justHtml;
});
```
